### PR TITLE
give some chances for old browsers

### PR DESCRIPTION
**Pull request by RobinQu**
support for GET :resource/destroy and POST :resource/update

### CODE REVIEW

**Comment by karl-gustav** [comment]
Out of curiosity; what browsers/versions does not support PUT/DELETE?

**Comment by RobinQu** [comment]
Basic html anchors cannot change its http method when sending requests.

**Comment by vendethiel** [comment]
which is why we have `methodOverride`, isn't it?

**Comment by emmanuel** [comment]
I don't think there is any place for `GET /resource/destroy` to be interpreted as a `DELETE`. That is out of alignment with HTTP semantics in important ways. 

Look up the [history of the Google Web Accelerator](http://37signals.com/svn/archives2/google_web_accelerator_hey_not_so_fast_an_alert_for_web_app_designers.php) for some concrete examples of what can happen when you disregard the semantics of the protocol.

**Comment by tj** [comment]
eek yeah GET should absolutely not destroy data, GET should be idempotent.

**Pull request closed without merging**
