### PR TITLE
Nested Resources

### PR DESCRIPTION
**Pull request by gf3**
- Resources may be nested.
- Basic singularisation rules.
- Tests.

### CODE REVIEW

**Comment by gf3** [comment]
Boom, did you are unimpressed?

**Comment by gf3** [comment]
Updated with the ability to pass a `Resource` as a parent and functionality for deeply nested resources. As well as tests :)

**Comment by tj** [comment]
weird github didnt notify me of these messages haha

**Comment by tj** [comment]
doing things a bit differently, feel fee to check it out

**Pull request closed without merging**
