### PR TITLE
Support for Express 4.x

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by itayadler** [comment]
+1 Just tested your branch with express 4.0 and it works fine for me

**Comment by mgcrea** [comment]
:+1:

**Comment by niftylettuce** [comment]
I'll merge and publish this to NPM

**Comment by vendethiel** [comment]
:+1: gratz

**Comment by 161chihuahuas** [comment]
:thumbsup:

**Comment by drewhamlett** [comment]
:thumbsup:

**Comment by niftylettuce** [comment]
One thing that isn't in yet is support for `.resource` on the new Router stuff in Express 4.x.

I think we should add that if we're going to keep using `express-resource`, otherwise you can't do a custom router and then do `customRouter.resource` as-is.

**Comment by bra1n** [comment]
:+1: 
When will this be on NPM?

Also, the way I see it, the Readme should be updated, right?

```
var express = require('express')
  , Resource = require('express-resource')
  , app = express();
```

should be replaced with

```
var express = require('express')
  , app = express();
require('express-resource')(app);
```

**Comment by cjroth** [comment]
+1

**Comment by cjroth** [comment]
@niftylettuce this might not be an issue with your code but it looks like the "default" content type isn't working with Express 4 yet - in express 4, req.format is undefined which seems to be causing it to literally look for an "undefined" property instead of a "default" property. I will look into this further when I get a chance.

**Comment by sendyhalim** [comment]
+1 bro :yum:

**Comment by Anachron** [comment]
Bump, I really want this inside my express 4 app :+1:

**Comment by fayimora** [comment]
ping @niftylettuce

**Comment by niftylettuce** [comment]
@fayimora @Anachron this isn't supported in 4.x because of the router issue I mentioned above

**Comment by Anachron** [comment]
@niftylettuce it's okay, I don't use this library anymore, since I need 4.0 express. :+1:

**Comment by kevindoole** [comment]
I came here because i was curious to see if there was already a PR to deal with that `express deprecated app.del` notice. Otherwise, for my needs this package seems to be working nicely witrh express4. 

In any case, is there any chance this package is gonna be updated in the future?

**Comment by niftylettuce** [comment]
sorry if anyone wants to submit a new PR that is tested etc and works or something go for it then ping me and email niftylettuce@gmail.com - I've been using Koa a ton and haven't touched Express in forever.

**Pull request closed without merging**
